version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # install node 12

  pre_build:
    commands:
      # install dependencies
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - npm run build
  
  artifacts:
    files:
      - "**/*"files:
      - template.yml
      - README.md
      - package.json
      - node_modules/**/*
      - public/**/*
      - src/**/*
      - CONTRIBUTING.md


      discard-paths: no
      base-directory: dist
