version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # install node 12
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs

  pre_build:
    commands:
      # install dependencies
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo building...
      - npm run build
  
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
